"""Content-addressed image cache — dedup provider API calls across reruns.

The cache wraps `images.generate()`: on a hit we copy bytes from
`{renders_dir}/_cache/images/` into the scene's work_dir instead of
calling the provider. Keyed by sha256(provider || model || aspect ||
prompt) so a provider swap invalidates cleanly.
"""
from __future__ import annotations

from datetime import timedelta
from pathlib import Path
from unittest.mock import patch


def test_compute_key_is_deterministic_and_input_sensitive():
    from app.services.image_cache import compute_key

    k1 = compute_key("wanx", "m", "9:16", "a cat")
    assert k1 == compute_key("wanx", "m", "9:16", "a cat")
    assert len(k1) == 64

    # Any input component changing must flip the hash.
    assert k1 != compute_key("dalle", "m", "9:16", "a cat")
    assert k1 != compute_key("wanx", "m2", "9:16", "a cat")
    assert k1 != compute_key("wanx", "m", "1:1", "a cat")
    assert k1 != compute_key("wanx", "m", "9:16", "a cat ")


def test_generate_caches_identical_prompts(client, tmp_path, monkeypatch):
    """Second call with the same prompt must NOT invoke the provider."""
    from app.config import settings
    from app.services import images

    monkeypatch.setattr(settings, "renders_dir", str(tmp_path / "renders"))
    monkeypatch.setattr(settings, "image_provider", "wanx")

    calls: list[Path] = []

    def fake_wanx(prompt, out_path, aspect):
        calls.append(Path(out_path))
        Path(out_path).write_bytes(b"\x89PNG\r\n\x1a\npixel-bytes")

    out1 = tmp_path / "scene_a.png"
    out2 = tmp_path / "scene_b.png"

    with patch("app.services.images._wanx_generate", side_effect=fake_wanx):
        images.generate("a moonlit circus tent", out1, aspect="9:16")
        images.generate("a moonlit circus tent", out2, aspect="9:16")

    assert len(calls) == 1, "provider should only fire on the first call"
    assert out1.exists() and out2.exists()
    # Hit copied bytes from the cache blob, so contents match.
    assert out1.read_bytes() == out2.read_bytes()


def test_generate_different_prompts_do_not_share_cache(client, tmp_path, monkeypatch):
    from app.config import settings
    from app.services import images

    monkeypatch.setattr(settings, "renders_dir", str(tmp_path / "renders"))
    monkeypatch.setattr(settings, "image_provider", "wanx")

    seen: list[str] = []

    def fake_wanx(prompt, out_path, aspect):
        seen.append(prompt)
        Path(out_path).write_bytes(b"\x89PNG" + prompt.encode())

    with patch("app.services.images._wanx_generate", side_effect=fake_wanx):
        images.generate("prompt A", tmp_path / "a.png")
        images.generate("prompt B", tmp_path / "b.png")

    assert seen == ["prompt A", "prompt B"]


def test_generate_invalidates_on_provider_swap(client, tmp_path, monkeypatch):
    """Same prompt under a different provider must re-fire — the cache
    key bakes in provider+model, so a config swap shouldn't serve bytes
    generated by the old provider."""
    from app.config import settings
    from app.services import images

    monkeypatch.setattr(settings, "renders_dir", str(tmp_path / "renders"))

    monkeypatch.setattr(settings, "image_provider", "wanx")
    wanx_calls: list[str] = []

    def fake_wanx(prompt, out_path, aspect):
        wanx_calls.append(prompt)
        Path(out_path).write_bytes(b"WANX")

    dalle_calls: list[str] = []

    def fake_dalle(prompt, out_path, aspect):
        dalle_calls.append(prompt)
        Path(out_path).write_bytes(b"DALLE")

    with (
        patch("app.services.images._wanx_generate", side_effect=fake_wanx),
        patch("app.services.images._dalle_generate", side_effect=fake_dalle),
    ):
        images.generate("same prompt", tmp_path / "w.png")
        monkeypatch.setattr(settings, "image_provider", "dalle")
        images.generate("same prompt", tmp_path / "d.png")

    assert len(wanx_calls) == 1
    assert len(dalle_calls) == 1
    assert (tmp_path / "w.png").read_bytes() == b"WANX"
    assert (tmp_path / "d.png").read_bytes() == b"DALLE"


def test_cache_disabled_always_fires_provider(client, tmp_path, monkeypatch):
    from app.config import settings
    from app.services import images

    monkeypatch.setattr(settings, "renders_dir", str(tmp_path / "renders"))
    monkeypatch.setattr(settings, "image_provider", "wanx")
    monkeypatch.setattr(settings, "image_cache_enabled", False)

    calls: list[str] = []

    def fake_wanx(prompt, out_path, aspect):
        calls.append(prompt)
        Path(out_path).write_bytes(b"\x89PNG")

    with patch("app.services.images._wanx_generate", side_effect=fake_wanx):
        images.generate("p", tmp_path / "a.png")
        images.generate("p", tmp_path / "b.png")

    assert len(calls) == 2


def test_cache_miss_refills_when_blob_deleted(client, tmp_path, monkeypatch):
    """If the cached blob file is gone (manual rm, _cache/ wiped), the
    next call treats it as a miss and re-fires the provider rather than
    silently serving an empty/missing file."""
    from app.config import settings
    from app.services import image_cache, images

    monkeypatch.setattr(settings, "renders_dir", str(tmp_path / "renders"))
    monkeypatch.setattr(settings, "image_provider", "wanx")

    calls: list[str] = []

    def fake_wanx(prompt, out_path, aspect):
        calls.append(prompt)
        Path(out_path).write_bytes(b"\x89PNG")

    with patch("app.services.images._wanx_generate", side_effect=fake_wanx):
        images.generate("p", tmp_path / "a.png")
        # Nuke the cache blob dir but leave the DB row.
        import shutil
        shutil.rmtree(image_cache.cache_root())
        images.generate("p", tmp_path / "b.png")

    assert len(calls) == 2


def test_cache_only_charges_cost_on_miss(client, tmp_path, monkeypatch):
    """record_image should be called on miss, skipped on hit — otherwise
    the cost dashboard double-counts cached scenes."""
    from app.config import settings
    from app.services import images

    monkeypatch.setattr(settings, "renders_dir", str(tmp_path / "renders"))
    monkeypatch.setattr(settings, "image_provider", "wanx")

    def fake_wanx(prompt, out_path, aspect):
        Path(out_path).write_bytes(b"\x89PNG")

    with (
        patch("app.services.images._wanx_generate", side_effect=fake_wanx),
        patch("app.services.cost.record_image") as record,
    ):
        images.generate("p", tmp_path / "a.png")
        images.generate("p", tmp_path / "b.png")

    assert record.call_count == 1


# ---------- Prune LRU-stale cache rows ----------


def test_prune_stale_image_cache_removes_old_rows(client, tmp_path, monkeypatch):
    from app.clock import utc_now
    from app.config import settings
    from app.db import SessionLocal
    from app.models import ImageAssetCache
    from app.services import image_cache, render_retention

    monkeypatch.setattr(settings, "renders_dir", str(tmp_path / "renders"))

    blob_old = image_cache.cache_root() / "aa" / "old.png"
    blob_old.parent.mkdir(parents=True, exist_ok=True)
    blob_old.write_bytes(b"old-bytes")

    blob_new = image_cache.cache_root() / "bb" / "new.png"
    blob_new.parent.mkdir(parents=True, exist_ok=True)
    blob_new.write_bytes(b"new-bytes")

    db = SessionLocal()
    try:
        db.add_all([
            ImageAssetCache(
                prompt_hash="old" + "0" * 61,
                provider="wanx", model="m", aspect="9:16",
                file_path=str(blob_old), bytes=9,
                created_at=utc_now() - timedelta(days=90),
                last_used_at=utc_now() - timedelta(days=60),
                hit_count=0,
            ),
            ImageAssetCache(
                prompt_hash="new" + "0" * 61,
                provider="wanx", model="m", aspect="9:16",
                file_path=str(blob_new), bytes=9,
                created_at=utc_now() - timedelta(days=90),
                last_used_at=utc_now() - timedelta(days=1),
                hit_count=5,
            ),
        ])
        db.commit()
    finally:
        db.close()

    db = SessionLocal()
    try:
        res = render_retention.prune_stale_image_cache(db, max_age_days=30)
    finally:
        db.close()

    assert res["removed_count"] == 1
    assert res["freed_bytes"] == 9
    assert not blob_old.exists()
    assert blob_new.exists()

    db = SessionLocal()
    try:
        assert db.get(ImageAssetCache, "old" + "0" * 61) is None
        assert db.get(ImageAssetCache, "new" + "0" * 61) is not None
    finally:
        db.close()


def test_prune_endpoint_includes_image_cache(client, tmp_path, monkeypatch):
    """POST /packages/prune-renders should sweep the image cache too."""
    from app.clock import utc_now
    from app.config import settings
    from app.db import SessionLocal
    from app.models import ImageAssetCache
    from app.services import image_cache

    monkeypatch.setattr(settings, "renders_dir", str(tmp_path / "renders"))

    blob = image_cache.cache_root() / "cc" / "stale.png"
    blob.parent.mkdir(parents=True, exist_ok=True)
    blob.write_bytes(b"x" * 100)

    db = SessionLocal()
    try:
        db.add(ImageAssetCache(
            prompt_hash="c" * 64,
            provider="wanx", model="m", aspect="9:16",
            file_path=str(blob), bytes=100,
            created_at=utc_now() - timedelta(days=90),
            last_used_at=utc_now() - timedelta(days=60),
            hit_count=0,
        ))
        db.commit()
    finally:
        db.close()

    res = client.post("/packages/prune-renders?max_age_days=30")
    assert res.status_code == 200
    body = res.json()
    assert "image_cache" in body
    assert body["image_cache"]["removed_count"] == 1
    assert not blob.exists()
